Models/Customer.cs
using System;
namespace team011.Models
{
    public class Customer
    {
       
        public int customerID { get; set; }
        public string email { get; set; }
        public string phone_number { get; set; }
        public string street_address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string postal_code { get; set; }
        public bool isIndividual { get; set; }
        public string driver_license { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string tax_ID { get; set; }
        public string contact_title { get; set; }
        public string contact_name { get; set; }
        public string business_name { get; set; }
        public string lastURL { get; set; }
        public string customerName { get; set; }

        public string concat_customerName_identityID { get; set; }
    }
}

Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using team011.Helper;
using team011.Models;
using System.Diagnostics;


// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace team011.Controllers
{
    public class CustomerController : Controller
    {
        // GET: /<controller>/
        public IActionResult LookupCustomerForm()
        {

            //ViewBag.customer= "this is look up ustomer view";
            return View();
        }

        public JsonResult getCustomer(string customerID, bool isIndividual, string lastURL)
        {
            SqlCommand cmd;
            SqlConnection cnn;
            SqlDataReader reader;
            cnn = ConnectionHelper.openConnection();

            var customer = new Customer();
            customer.customerID = -1; //default
            if (isIndividual)
            {
                var driver_license = customerID;
                var sqlString = "SELECT * FROM Individual i,Customer c WHERE i.customerID = c.customerID AND driver_license = @driver_license";
                cmd = new SqlCommand(sqlString, cnn);
                cmd.Parameters.AddWithValue("@driver_license", driver_license);
                reader = cmd.ExecuteReader();
                while (reader.Read())
                {
                    customer.customerID = (int)reader["customerID"];
                    customer.email = reader["email"].ToString();
                    customer.phone_number = reader["phone_number"].ToString();
                    //customer.add_by_user_name = reader["add_by_user_name"].ToString();
                    customer.street_address = reader["street_address"].ToString();
                    customer.city = reader["city"].ToString();
                    customer.state = reader["state"].ToString();
                    customer.postal_code = reader["postal_code"].ToString();
                    customer.driver_license = reader["driver_license"].ToString();
                    customer.first_name = reader["first_name"].ToString();
                    customer.last_name = reader["last_name"].ToString();
                    customer.customerName = reader["first_name"].ToString() + ", " + reader["last_name"].ToString();



                }
            }
            else
            {
                var tax_ID = customerID;
                var sqlString = "SELECT * FROM Business b,Customer c WHERE b.customerID = c.customerID AND tax_ID = @tax_ID";
                cmd = new SqlCommand(sqlString, cnn);
                cmd.Parameters.AddWithValue("@tax_ID", tax_ID);
                reader = cmd.ExecuteReader();
                while (reader.Read())
                {
                    customer.customerID = (int)reader["customerID"];
                    customer.email = reader["email"].ToString();
                    customer.phone_number = reader["phone_number"].ToString();
                    //customer.add_by_user_name = reader["add_by_user_name"].ToString();
                    customer.street_address = reader["street_address"].ToString();
                    customer.city = reader["city"].ToString();
                    customer.state = reader["state"].ToString();
                    customer.postal_code = reader["postal_code"].ToString();
                    customer.tax_ID = reader["tax_ID"].ToString();
                    customer.contact_title = reader["contact_title"].ToString();
                    customer.contact_name = reader["contact_name"].ToString();
                    customer.business_name = reader["business_name"].ToString();
                    customer.customerName = customer.business_name;
                }
            }
            customer.isIndividual = isIndividual;

            return Json(customer);
        }

        public IActionResult AddCustomerForm()
        {
            return View();
        }




        [HttpPost]
        public JsonResult addCommon(bool isIndividual,
                    string email,
                    string phone_number,
                    string add_by_user_name,
                    string street_address,
                    string city,
                    string state,
                    string postal_code,
                    string driver_license,
                    string first_name,
                    string last_name,
                    string tax_ID,
                    string contact_title,
                    string contact_name,
                    string business_name)
        {


            SqlCommand cmd;
            SqlConnection cnn;
            SqlDataReader reader;
           

            Customer customer = new Customer();
            customer.isIndividual = isIndividual;
            customer.email = email;
            customer.phone_number = phone_number;
            customer.street_address = street_address;
            customer.city = city;
            customer.state = state;
            customer.postal_code = postal_code;
            customer.driver_license = driver_license;
            customer.first_name = first_name;
            customer.last_name = last_name;
            customer.tax_ID = tax_ID;
            customer.contact_title = contact_title;
            customer.contact_name = contact_name;
            customer.business_name = business_name;

            

            var sqlInsertCustomer = "INSERT INTO Customer (email,phone_number,street_address, city, state, postal_code) " +
                "VALUES (@email,@phone_number,@street_address,@city,@state,@postal_code)";
            var sqlInsertCustomerNoEmail = "INSERT INTO Customer (email,phone_number,street_address, city, state, postal_code) " +
                "VALUES (null,@phone_number,@street_address,@city,@state,@postal_code)";

            cnn = ConnectionHelper.openConnection();
            if (customer.email != null)
            {
                cmd = new SqlCommand(sqlInsertCustomer, cnn);
                cmd.Parameters.AddWithValue("@email", email);
            }
            else
            {
                cmd = new SqlCommand(sqlInsertCustomerNoEmail, cnn);

            }
            cmd.Parameters.AddWithValue("@phone_number", phone_number);
            cmd.Parameters.AddWithValue("@street_address", street_address);
            cmd.Parameters.AddWithValue("@city", city);
            cmd.Parameters.AddWithValue("@state", state);
            cmd.Parameters.AddWithValue("@postal_code", postal_code);
            cmd.ExecuteNonQuery();
            cmd.Dispose();



            var sqlGetCustomerID = "SELECT CustomerID FROM Customer WHERE phone_number = @phone_number " +
                " AND street_address = @street_address AND city = @city AND state = @state AND postal_code = @postal_code";

            cmd = new SqlCommand(sqlGetCustomerID, cnn);
            cmd.Parameters.AddWithValue("@phone_number", phone_number);
            cmd.Parameters.AddWithValue("@street_address", street_address);
            cmd.Parameters.AddWithValue("@city", city);
            cmd.Parameters.AddWithValue("@state", state);
            cmd.Parameters.AddWithValue("@postal_code", postal_code);

            reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                customer.customerID = (int) reader["customerID"];   
            }

            var isAdded = 0;
           
            if (customer.isIndividual)
            {
                var sqlInsertIndividual = "INSERT INTO Individual (driver_license,first_name,last_name,customerID) " +
                "VALUES (@driver_license,@first_name,@last_name,@customerID)";
                cmd = new SqlCommand(sqlInsertIndividual, cnn);
                cmd.Parameters.AddWithValue("@driver_license", driver_license);
                cmd.Parameters.AddWithValue("@first_name", first_name);
                cmd.Parameters.AddWithValue("@last_name", last_name);
                cmd.Parameters.AddWithValue("@customerID", customer.customerID);
                try
                {
                    isAdded = cmd.ExecuteNonQuery();
                }
                catch (Exception ex)
                {

                }
                
                cmd.Dispose();

            }
            else
            {
                var sqlInsertIndividual = "INSERT INTO Business (tax_ID,contact_title,contact_name,business_name,customerID) " +
                "VALUES (@tax_ID,@contact_title,@contact_name,@business_name,@customerID)";
                cmd = new SqlCommand(sqlInsertIndividual, cnn);
                cmd.Parameters.AddWithValue("@tax_ID", tax_ID);
                cmd.Parameters.AddWithValue("@contact_title", contact_title);
                cmd.Parameters.AddWithValue("@contact_name", contact_name);
                cmd.Parameters.AddWithValue("@business_name", business_name);
                cmd.Parameters.AddWithValue("@customerID", customer.customerID);
                
                isAdded = cmd.ExecuteNonQuery();
                cmd.Dispose();
            }
            var success = false;
            if (isAdded == 0)
            {
                success = false;
            }
            else
            {
                success = true;
            }
            return Json(success);
        }

    }
}

Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
//using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
//using team011.Helper;

using System.Data.SqlClient;
using team011.Helper;
using team011.Models;
using Microsoft.AspNetCore.Http;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace team011.Controllers
{
    public class UserController : Controller
    {

        public IActionResult Index()
        {

            return View();


        }
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return View("Index");
        }
       
        //public JsonResult checkUserLogin(string username, string password)
        public JsonResult checkUserLogin(Users user)
        {
            SqlCommand cmd;
            SqlConnection cnn;
            SqlDataReader reader;
            var isLogedin = false;
            var loggedInUser = new Users();
            var userCTE = "WITH UserpermissionCTE AS"+
                "(SELECT user_name, 'ServiceWriter'as Userrole FROM ServiceWriter " +
                "UNION "+
                "SELECT user_name, 'SalesPeople' FROM SalesPeople " +
                "UNION "+
                "SELECT user_name, 'Owner' FROM Owner "+
                "UNION "+
                "SELECT user_name, 'Manager' FROM Manager " +
                "UNION "+
                "SELECT user_name, 'InventoryClerk' FROM InventoryClerk)";
            var selectsql = "select u.user_name, u.password, u.first_name, u.last_name, cte.Userrole" +
                " from UserpermissionCTE cte INNER JOIN [dbo].[Users] u on cte.[user_name] = u.[user_name] " +
                "WHERE u.user_name = @username AND u.password = @password";
            var sql = userCTE + selectsql;

            cnn = ConnectionHelper.openConnection();
            cmd = new SqlCommand(sql, cnn);
            cmd.Parameters.AddWithValue("@username", user.user_name);
            cmd.Parameters.AddWithValue("@password", user.password);
            //cmd.Parameters.AddWithValue("@username", username);
            //cmd.Parameters.AddWithValue("@password", password);
            reader = cmd.ExecuteReader();
            var count = 0;
            while (reader.Read())
            {
                count++;

                isLogedin = true;

                loggedInUser.first_name = reader["first_name"].ToString();
                loggedInUser.last_name = reader["last_name"].ToString();
                loggedInUser.user_name = reader["user_name"].ToString();
                loggedInUser.user_role = reader["Userrole"].ToString();

            }
            ConnectionHelper.closeConnection(cnn, cmd, reader);
            if (isLogedin)
            {
                //if count = 5 then the role should be Rolando
                if (count == 5)
                {
                    HttpContext.Session.SetString("loggedUserRole", "Owner");

                }
                else
                {
                    HttpContext.Session.SetString("loggedUserRole", loggedInUser.user_role);
                }
                HttpContext.Session.SetString("loggedUserFullName", loggedInUser.first_name + " " + loggedInUser.last_name);
                HttpContext.Session.SetString("loggedUserName", loggedInUser.user_name);



                return Json(new { success = isLogedin, loggedInUser = loggedInUser });


            }
            else
            {
                return Json(new { success = isLogedin});
            }
           // HttpContext.Session.SetString("loggedUserUserName", loggedInUser.user_name);


        }
    }
}

Views/Shared/_Customer.cshtml
@model team011.Models.Customer
@ViewBag.customer
@using Microsoft.AspNetCore.Http;

@inject IHttpContextAccessor HttpContextAccessor

<div class="container">
    <div>
        <h6 id="DL">Customer Driver's License:</h6>
        <h6 id="TaxID">Customer TaxID:</h6>
        <form id="customerForm" name="customerForm" class="customer">
            <div class="form-group row">
                <div class="col-sm-10" style="display:inline-flex">

                    <input type="text" id="txtCustomerID" placeholder="Enter Customer ID Here" class="form-control" required/>
                    <span class="error" style="color:red; display:none">*</span>

                </div>

                <div class="col-sm-2">
                    <input id="btnsearchcustomer" type="submit" style="bottom:0" class="btn btn-info" value="Search" />
                </div>
            </div>
            <div class="row">
                <div class="col"></div>
                <div class="col">
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="customerType" id="radioIndividual" value="individual" required>
                        <label class="form-check-label" for="radioIndividual">Individual</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="customerType" id="radioBusiness" value="business">
                        <label class="form-check-label" for="radioBusiness">Business</label>
                    </div>

                </div>

                <div class="col"></div>
            </div>
            <div id="response"></div>
            <div id="responseform">

                <div class="row">
                    <div class="col-sm-6">
                        <label>Customer Name:</label>
                        <div>
                            <input type="text" class="form-control" id="ReturnedName" disabled />
                        </div>
                    </div>

                    <div class="col-sm-6">
                        <label>Phone Number:</label>
                        <div>
                            <input type="text" class="form-control" id="ReturnedPhoneNumber" disabled />
                        </div>

                    </div>
                </div>
                <div class="row">

                    <div class="col">
                        <label>Street:</label>
                        <div>
                            <input type="text" class="form-control" id="ReturnedStreet" disabled />
                        </div>

                    </div>
                </div>
                <div class="row">

                    <div class="col-sm-4">
                        <label>City:</label>
                        <div>
                            <input type="text" class="form-control" id="ReturnedCity" disabled />
                        </div>

                    </div>

                    <div class="col-sm-4">
                        <label>State:</label>
                        <div>
                            <input type="text" class="form-control" id="ReturnedState" disabled />
                        </div>

                    </div>

                    <div class="col-sm-4">
                        <label>Postal Code:</label>
                        <div>
                            <input type="text" class="form-control" id="ReturnedPostalCode" disabled />
                        </div>

                    </div>
                </div>


            </div>

            <div class="form-group row">
                <div class="col">
                    <a href="@Url.Action("AddCustomerForm","Customer")" id="addCustomerbtn">
                        <input id="addCustomerbtn" type="button" class="btn btn-primary" value="Add Customer" />
                    </a>
                </div>

            </div>

            <div id="customerInfo">
                <p id="text">Customer id:</p>
                <p id="ReturnedCustomerID"></p>
                <p id="ReturnedCustomerName"></p>
            </div>


        </form>
        <hr />
    </div>


</div>
<script>



    $(function () {

        $("#addCustomerbtn").hide();
        $("#customerInfo").hide();
        $("#TaxID").hide();
        $("#response").hide();
        $("#responseform").hide();

        $("#radioIndividual").on("change", function () {
            $("#DL").show();
            $("#TaxID").hide();
        });

        $("#radioBusiness").on("change", function () {
            $("#DL").hide();
            $("#TaxID").show();
        });

        var id = -1;

        $("#customerForm").submit(function (e) {
            

            e.preventDefault();
            var customer_ID = $("#txtCustomerID").val();
            var isIndividual = document.getElementById('radioIndividual').checked;

            $.ajax({
                type: "GET",
                url: '@Url.Action("getCustomer", "Customer")',
                data: { "CustomerID": customer_ID, "isIndividual": isIndividual},
                success: function (response) {
                    if (response.customerID != -1) {
                        
                        $("#responseform").show();
                        document.getElementById("ReturnedCustomerID").innerHTML = response.customerID;
                       
                        document.getElementById("ReturnedCustomerName").innerHTML = response.customerName;
                        document.getElementById("ReturnedName").value = response.customerName;

                        document.getElementById("ReturnedPhoneNumber").value = response.phone_number;
                        document.getElementById("ReturnedStreet").value = response.street_address;
                        document.getElementById("ReturnedCity").value = response.city;
                        document.getElementById("ReturnedState").value = response.state;
                        document.getElementById("ReturnedPostalCode").value = response.postal_code;


                        $('#showSelectBtn').show();
                        $("#response").hide();
                        $("#addCustomerbtn").hide();

                    }
                    else {
                        document.getElementById("response").innerHTML = "Customer does not exist.";
                        document.getElementById("customerName").value = "";
                        $("#addCustomerbtn").show();
                        $("#response").show();
                        $("#responseform").hide();
                        $('#showSelectBtn').hide();


                    }
                }
            })
        });

    });


</script>

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;

@inject IHttpContextAccessor HttpContextAccessor




<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - team011</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/css/site.css" />
    @*<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>*@

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous"></script>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js" integrity="sha512-37T7leoNS06R80c8Ulq7cdCDU5MNQBwlYoy1TX/WUsLFC2eYNqtKlV0QjH7r8JpG/S0GUMZwebnVFLPd6SU5yg==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/additional-methods.min.js" integrity="sha512-XZEy8UQ9rngkxQVugAdOuBRDmJ5N4vCuNXCh8KlniZgDKTvf7zl75QBtaVG1lEhMFe2a2DuA22nZYY+qsI2/xA==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/4.6.1/js/bootstrap.min.js" integrity="sha512-UR25UO94eTnCVwjbXozyeVd6ZqpaAE9naiEUBK/A+QDbfSTQFhPGj5lOR6d8tsgbBk84Ggb5A3EkjsOgPRPcKA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.19.1/dist/bootstrap-table.min.css">
    <script src="https://unpkg.com/bootstrap-table@1.19.1/dist/bootstrap-table.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>





    <script src="https://cdn.datatables.net/1.11.3/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.0.1/js/dataTables.buttons.min.js"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.0.1/css/buttons.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.3/css/dataTables.bootstrap4.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/11.2.0/sweetalert2.min.css" integrity="sha512-xJUrflcxYcNngauImIUGqGQUxMHq3wD7mFKMDUOPyjg0sthw2JUw/AhxrGeoVorVsX1U7e0aUoeo4Cvm7LHGhw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/11.2.0/sweetalert2.min.js" integrity="sha512-BbhEY8ZvF5TicBw3nIPE5QA4tgPjQ8C3fIiY9c4UBSaRBmvFcY/qOD3FIBa30oBRbN6h/+KjzEMHGqI9tnbSIg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js" integrity="sha512-qTXRIMyZIFb8iQcfjXWCO8+M5Tbc38Qi5WzdPOYZHIlZpzBHG3L3by84BBBOiRGiEb7KKtAOAs5qYdUiZiQNNQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/js/all.min.js" integrity="sha512-fzff82+8pzHnwA1mQ0dzz9/E0B+ZRizq08yZfya66INZBz86qKTCt9MLU0NCNIgaMJCgeyhujhasnFUsYMsi0Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="#">Jaunty Jalopies</a>

            <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li class="nav-item @(ViewBag.Current == "Home" ? "active" : "") ">
                        <a class="nav-link" href="@Url.Action("Index","Home")">Home <span class="sr-only">(current)</span></a>
                    </li>
                    @if (@HttpContextAccessor.HttpContext.Session.GetString("loggedUserFullName") != null)
                    {
                        @*<li class="nav-item">
                            <a class="nav-link" href="@Url.Action("LookupCustomerForm", "Customer")">Customers</a>
                        </li>


                        if (@HttpContextAccessor.HttpContext.Session.GetString("loggedUserRole") == "SalesPeople" ||
                      @HttpContextAccessor.HttpContext.Session.GetString("loggedUserRole") == "Owner")
                        {
                            <li class="nav-item">

                                <a class="nav-link" href="@Url.Action("CreateTransactionForm", "SaleTransaction")">Sales Transaction</a>
                            </li>
                        }*@
                        if (@HttpContextAccessor.HttpContext.Session.GetString("loggedUserRole") == "ServiceWriter" ||
                     @HttpContextAccessor.HttpContext.Session.GetString("loggedUserRole") == "Owner")
                        {

                            <li class="nav-item @(ViewBag.Current == "RepairOrder" ? "active" : "") ">
                                <a class="nav-link " href="@Url.Action("Index", "RepairOrder")">Repair Orders</a>
                            </li>
                        }
                        if (@HttpContextAccessor.HttpContext.Session.GetString("loggedUserRole") == "Manager" ||
                    @HttpContextAccessor.HttpContext.Session.GetString("loggedUserRole") == "Owner")
                        {
                            <li class="nav-item @(ViewBag.Current == "Report" ? "active" : "") ">
                                <a class="nav-link " href="@Url.Action("Index", "Report")">Reports</a>
                            </li>

                        }
                    }
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    @if (@HttpContextAccessor.HttpContext.Session.GetString("loggedUserFullName") != null)
                    {
                        <label id="lblLoggedinUser">
                            Welcome, @HttpContextAccessor.HttpContext.Session.GetString("loggedUserFullName")
                        </label>
                        <a href='@Url.Action("Logout", "User")'>
                            <input class="btn btn-outline-success my-2 my-sm-0" id="btnNavLogout" type="button" value="Log Out" />
                        </a>
                    }
                    else
                    {
                        <a href='@Url.Action("Index", "User")'>
                            <input class="btn btn-outline-success my-2 my-sm-0" id="btnNavLogin" type="button" value="Log In" />
                        </a>


                    }



                </form>
            </div>
        </nav>
    </header>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - team011 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
    </body>
</html>


<script>

 

    priceelelist = document.getElementsByClassName("price");
    for (index = 0; index < priceelelist.length; ++index) {
        priceelelist[index].setAttribute("oninput", "validate2decimals(this)")
    }

    intnumberlist = document.getElementsByClassName("intnumber");
    for (index = 0; index < intnumberlist.length; ++index) {
        intnumberlist[index].setAttribute("onkeypress", "validateintnumber(this)")
    }


    var validate2decimals = function (e) {
        var t = e.value;
        e.value = (t.indexOf(".") >= 0) ? (t.substr(0, t.indexOf(".")) + t.substr(t.indexOf("."), 3)) : t;
    }

    var validateintnumber = function (e) {
        e.value = Math.round(e.value);
    }
  
</script>