Controllers/SaleTransactionController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using team011.Helper;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace team011.Controllers
{
    public class SaleTransactionController : Controller
    {
        // GET: /<controller>/
        public IActionResult CreateTransactionForm(string VIN )
        {
            ViewBag.VIN = VIN;

            SqlCommand cmd;
            SqlConnection cnn;
            SqlDataReader reader;
            cnn = ConnectionHelper.openConnection();

            
            var invoice_pricesql = "SELECT invoice_price FROM Vehicle WHERE Vehicle.VIN = @vin ";
            cmd = new SqlCommand(invoice_pricesql, cnn);
            cmd.Parameters.AddWithValue("@vin", VIN);
            reader = cmd.ExecuteReader();

            if (reader.HasRows)
            {
                while (reader.Read())
                {
                    ViewBag.invoice_price = (decimal)reader["invoice_price"];
                }
            }



            
            ViewBag.customerID = 1;
            ViewBag.customer_name = "Customer not selected yet";
            return View();
        }

        public JsonResult CreateTransaction(string vin, int customerID, string salespeople, string sold_price, string sold_date)
        {
            SqlCommand cmd;
            SqlConnection cnn;

            cnn = ConnectionHelper.openConnection();
            var createTransactionSql = "INSERT INTO SalesTransaction Values( @vin, @customerID, @salespeople, @sold_price, @sold_date) ";
            //sql command
            cmd = new SqlCommand(createTransactionSql, cnn);

            cmd.Parameters.AddWithValue("@vin", vin);
            cmd.Parameters.AddWithValue("@customerID", customerID);
            cmd.Parameters.AddWithValue("@salespeople", salespeople);
            cmd.Parameters.AddWithValue("@sold_price", float.Parse(sold_price));
            cmd.Parameters.AddWithValue("@sold_date", DateTime.Parse(sold_date));
            cmd.ExecuteNonQuery();
            cmd.Dispose();
            cnn.Close();

            //return Json(new { Url = "~/Views/Vehicle/VehicleDetailForm.cshtml" });
            return Json(true);
        }



    }



}

Controllers/VehicleController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using team011.Helper;
using team011.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace team011.Controllers
{
    public class VehicleController : Controller
    {
        // GET: /<controller>/
        public IActionResult VehicleDetailForm(string VIN)
        {
            
            SqlCommand cmd;
            SqlConnection cnn;
            SqlDataReader reader;
            var vehicle = new Vehicle();          
            var customer = new Customer();
            vehicle.isSold = false;
            customer.isIndividual = false;
            vehicle.isSold = false;

            cnn = ConnectionHelper.openConnection();


            
            //sql command
            var vehicleETEsql = "WITH VehicleCTE AS( SELECT v.VIN, description, model_year, model_name, " +
                "invoice_price,manufacturer_name , inv_writer_user_name, add_date,  'Car' as vehicle_type " +
                "FROM Vehicle v INNER JOIN Car c on  v.VIN = c.VIN " +
                "UNION " +
                "SELECT v.VIN, description, model_year, model_name, invoice_price,manufacturer_name , inv_writer_user_name, add_date, " +
                "'Convertible' FROM Vehicle v INNER JOIN Convertible c on  v.VIN = c.VIN " +
                "UNION " +
                "SELECT v.VIN, description, model_year, model_name, invoice_price,manufacturer_name , inv_writer_user_name," +
                "add_date, 'Truck' FROM Vehicle v INNER JOIN Truck t on  v.VIN = t.VIN " +
                "UNION " +
                "SELECT v.VIN, description, model_year, model_name, invoice_price,manufacturer_name , inv_writer_user_name, " +
                "add_date, 'Van' FROM Vehicle v INNER JOIN Van  on  v.VIN = Van.VIN " +
                "UNION " +
                "SELECT v.VIN, description, model_year, model_name, invoice_price,manufacturer_name , inv_writer_user_name, " +
                "add_date, 'SUV' FROM Vehicle v INNER JOIN SUV s  on  v.VIN = s.VIN )";
            var selectsql = "SELECT VehicleHasColor.VIN, vehicle_type, model_year, manufacturer_name, " +
                "model_name, description, invoice_price, invoice_price * 1.25 as list_price, first_name, last_name, add_date, " +
                "STRING_AGG(color, ',') AS vehicle_color, "+
                "number_of_doors, roof_type, back_seat_count, cargo_capacity, cargo_cover_type, number_of_rear_axies, has_driver_side_back_door, number_of_cupholder, drivetrain_type "+
                "FROM VehicleCTE INNER JOIN VehicleHasColor " +
                "on VehicleCTE.VIN = VehicleHasColor.VIN INNER JOIN Users on Users.user_name=inv_writer_user_name "+
                "LEFT JOIN Car on VehicleCTE.VIN=Car.VIN LEFT JOIN Convertible on VehicleCTE.VIN=Convertible.VIN LEFT JOIN Truck on VehicleCTE.VIN=Truck.VIN "+
                "LEFT JOIN Van on VehicleCTE.VIN=Van.VIN LEFT JOIN SUV on VehicleCTE.VIN=SUV.VIN "+
                "WHERE VehicleCTE.VIN = @vin " +
                "GROUP by VehicleHasColor.VIN, vehicle_type, model_year, manufacturer_name, model_name, description, invoice_price, invoice_price * 1.25,first_name, last_name, add_date, number_of_doors, roof_type, back_seat_count, cargo_capacity, cargo_cover_type, number_of_rear_axies, has_driver_side_back_door, number_of_cupholder, drivetrain_type ";

            var sql = vehicleETEsql + selectsql;
            cnn = ConnectionHelper.openConnection();
            cmd = new SqlCommand(sql, cnn);
            cmd.Parameters.AddWithValue("@vin", VIN);
            reader = cmd.ExecuteReader();
            if (reader.HasRows)
                {
                while (reader.Read())
                {
                    vehicle.VIN = (string)reader["VIN"];
                    vehicle.vehicle_type = (string)reader["vehicle_type"];
                    vehicle.model_year = (int)reader["model_year"];
                    vehicle.manufacturer_name = (string)reader["manufacturer_name"];
                    vehicle.model_name = (string)reader["model_name"];
                    vehicle.invoice_price = (decimal)reader["invoice_price"];
                    vehicle.list_price = decimal.Round((decimal)reader["list_price"], 2, MidpointRounding.AwayFromZero);
                    vehicle.first_name = (string)reader["first_name"];
                    vehicle.last_name = (string)reader["last_name"];
                    vehicle.add_date = (DateTime)reader["add_date"];
                    vehicle.vehicle_color = reader["vehicle_color"] != DBNull.Value ? (string)reader["vehicle_color"] : "";
                    vehicle.description = reader["description"] != DBNull.Value ? (string)reader["description"] : "";

                    if (vehicle.vehicle_type == "Car")
                    {
                        vehicle.number_of_doors = (int)reader["number_of_doors"];

                    }
                    else if (vehicle.vehicle_type == "Convertible")
                    {
                        vehicle.roof_type = (string)reader["roof_type"];
                        vehicle.back_seat_count = (int)reader["back_seat_count"];
                    }
                    else if (vehicle.vehicle_type == "Truck")
                    {
                        vehicle.cargo_capacity = (decimal)reader["cargo_capacity"];
                        vehicle.cargo_cover_type = reader["cargo_cover_type"] != DBNull.Value ? (string)reader["cargo_cover_type"]:"";
                        vehicle.number_of_rear_axies = (int)reader["number_of_rear_axies"];
                    }
                    else if (vehicle.vehicle_type == "Van")
                    {
                        vehicle.has_driver_side_back_door = (bool)reader["has_driver_side_back_door"];

                    }
                    else if (vehicle.vehicle_type == "SUV")
                    {
                        vehicle.number_of_cupholder = (int)reader["number_of_cupholder"];
                        vehicle.drivetrain_type = (string)reader["drivetrain_type"];
                    }
                }
                }
                

            var buyersql = "SELECT SalesTransaction.customerID, email, phone_number, street_address, city, state, postal_code, " +
                "sold_price, sales_writer_user_name, sold_price, transaction_date, U.first_name AS uf, U.last_name AS ul, " +
                "I.first_name as Indf, I.last_name as Indl, B.business_name, B.contact_name, B.contact_title "+
                "FROM SalesTransaction, Users AS U JOIN SalesPeople AS S on U.user_name=S.user_name, Customer AS C " +
                "LEFT JOIN Individual AS I on C.customerID=I.customerID LEFT JOIN Business AS B on C.customerID=B.customerID " +
                "WHERE SalesTransaction.VIN = @vin AND SalesTransaction.CustomerID = C.customerID " +
                "AND SalesTransaction.sales_writer_user_name=U.user_name;";
            cnn = ConnectionHelper.openConnection();
            cmd = new SqlCommand(buyersql, cnn);
            cmd.Parameters.AddWithValue("@vin", VIN);
            reader = cmd.ExecuteReader();
            if (reader.HasRows)
                {
                vehicle.isSold = true;
                    while (reader.Read())
                    {
                    customer.customerID = (int)reader["customerID"];
                    customer.email = reader["email"] != DBNull.Value ? (string)reader["email"] : "";
                    customer.phone_number = (string)reader["phone_number"];
                    customer.street_address = (string)reader["street_address"];
                    customer.city = (string)reader["city"];
                    customer.state = (string)reader["state"];
                    customer.postal_code = (string)reader["postal_code"];
                    if(reader["business_name"] != DBNull.Value)
                    {
                        customer.isIndividual = false;
                        customer.business_name = (string)reader["business_name"];
                        customer.contact_name = (string)reader["contact_name"];
                        customer.contact_title= (string)reader["contact_title"];
                    }
                    else
                    {
                        customer.isIndividual = true;
                        customer.first_name = (string)reader["Indf"];
                        customer.last_name = (string)reader["Indl"];
                    
                    }


                    vehicle.sold_price = (decimal)reader["sold_price"];
                    vehicle.sold_date = (DateTime)reader["transaction_date"];
                    vehicle.sales_people_name = (string)reader["uf"] + ", " + (string)reader["ul"];

                    }
                }

            var repairHistorys = new List<RepairOrder>();
            var repairHistorySQL = "SELECT B.business_name, I.first_name, I.last_name, R.start_date, complete_date, labor_charge, parts_cost, R.repair_starter, U.first_name AS uf, U.last_name AS ul " +
                "FROM Customer AS C LEFT OUTER JOIN Individual AS I on C.customerID=I.customerID  LEFT OUTER JOIN Business AS B on C.customerID=B.customerID, " +
                "RepairDetails AS R LEFT JOIN " +
                "(SELECT VIN, start_date, SUM (quantity*price) AS parts_cost FROM Part GROUP BY Part.VIN, Part.start_date) AS P " +
                "ON (R.start_date= P.start_date AND R.VIN=P.VIN) "+
                "JOIN USERS as U on R.repair_starter=U.user_name "+
                "WHERE R.customerID = C.customerID AND R.VIN = @vin  " +
                "ORDER BY R.start_date DESC, R.complete_date ASC; ";
              
            cmd = new SqlCommand(repairHistorySQL, cnn);
            cmd.Parameters.AddWithValue("@vin", VIN);

Views/SaleTransaction/CreateTransactionForm.cshtml
@{
    Layout = "~/views/shared/_layout.cshtml";
    var currentDate = (string)DateTime.Now.ToShortDateString();
    var currentUsername = @HttpContextAccessor.HttpContext.Session.GetString("loggedUserName");

    var minSoldPrice = decimal.Round((decimal)(decimal)ViewBag.invoice_price * (decimal)0.95, 2, MidpointRounding.AwayFromZero)+(decimal)0.01;

    var vin = ViewBag.VIN;
    var userrole = @HttpContextAccessor.HttpContext.Session.GetString("loggedUserRole");


}
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor

<div class="container">
        <div class="list-group-item">
            <div class="mx-auto font-weight-bold" style="width: 200px;">
                Create Sales Order
            </div>
            <div class="row">
                <div class="col text-center">VIN</div>
                <div class="col-7 text-left">@vin</div>

            </div>
        </div>
        <div class="list-group-item">

            <form id="customerForm">
                <partial name="_Customer" />
            </form>
            <div class="col">
                <input type="button" id="btnSelectCustomer" class="btn btn-info" value="Select Customer" />
            </div>

            <div class="form-group row">

            </div>

            <div class="form-group row">
                <div class="col">
                    <div class="col-sm-6">
                        <div id="card">
                            <h6>
                                Customer Selected:
                            </h6>
                            <div>
                                <input id="customerName" class="form-control " disabled value="" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            @*<div class="col">
            <div id="card" class="card">
                <div class="card-body">
                    <span>Customer ID: </span><span id="cID"></span>

                </div>
            </div>

        </div>*@


            @*<a href="@Url.Action("LookupCustomerForm","Customer")">
            <input type="button" class="btn btn-primary" value="Look Up Customer" />
        </a>
        <div class="col-8 text-center">Customer Selected as: @ViewBag.customer_name</div>*@
        </div>

        <div class="list-group-item">
            <div class="col-sm-12">
                <form id="salesTransactionForm">
                    <div class="form-group row">
                        <div class="col">
                            <h6>Sold Price: </h6>
                            @if (userrole == "Owner")
                            {
                                <input type="number" id="txtSoldPrice" required placeholder="Enter Sold Price Here" class="form-control" min="0" step="0.01" />
                            }
                            else
                            {
                                <input type="number" id="txtSoldPrice" required placeholder="cannot be less than @minSoldPrice" class="form-control" min="@minSoldPrice" step="0.01" />
                            }

                        </div>
                        <div class="col">
                            <h6>Sold date: @currentDate</h6>
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col">
                            @*<a href="@Url.Action("VehicleDetailForm","Vehicle")?VIN=@ViewBag.VIN">*@
                            <input type="submit" id="btnCreateTransaction" class="btn btn-primary" value="Create Transaction" />
                            @*</a>*@
                        </div>



                    </div>



                </form>

            </div>
            
        </div>
</div>

<script>
    $(document).ready(function () {

        $('#btnSelectCustomer').on('click', function (e) {
            ReturnedCustomerName = document.getElementById("ReturnedCustomerName").innerHTML;
            document.getElementById("customerName").value = ReturnedCustomerName;
            returnedCustomerID = document.getElementById("ReturnedCustomerID").innerHTML;
            
        });


        $('#salesTransactionForm').submit( function (e) {
            e.preventDefault();

            var sold_price = $('#txtSoldPrice').val();

            console.log('@vin');
            console.log(returnedCustomerID);
            console.log(sold_price);
            console.log('@currentUsername');
            console.log('@currentDate');

            if (returnedCustomerID == -1) {
                console.log("no customer");
            }
            else {
                CreateTransaction('@vin', returnedCustomerID, "@currentUsername", sold_price, '@currentDate');
            }





            @*if (currentUserrole !== 'Owner') {
                if (updatedLaborcharge < laborcharge) {
                    $('#txtlaborcharge').val(laborcharge)
                    $("#laborchargeerror").show()
                    console.log('error')
                    return false
                }
                else {
                    $("#laborchargeerror").hide()
                    addPart(newPartArray)
                    updaterepairOrder(updatedLaborcharge, updateDecription, VIN, stateDate
                }
            }*@



        })

    });

    function CreateTransaction(vin, customerID, currentUsername, sold_price, sold_date) {
        console.log("in the function")
        $.ajax({
            type: "POST",
            url: '@Url.Action("CreateTransaction", "SaleTransaction")',
                 data: {
                     'vin': vin,
                     'customerID': customerID,
                     'salespeople': currentUsername,
                     'sold_price': sold_price,
                     'sold_date': sold_date
            },
            success: function (response) {
                if (response) {

                    window.location.href = "@Url.Action("VehicleDetailForm","Vehicle")?VIN=@vin";
                }
                console.log("create sales transaction")
            }



        })

    }


</script>